### PR TITLE
Add user add to the social account connection

### PR DESCRIPTION
**Pull request by mihaisolomon**

### CODE REVIEW

**Comment by lao9s** [comment]
Hey, thanks for this! 
I analyzed the code and didn't understand why we needed `user_id` in our table. We will not do anything with this information and we do not intend to use it anywhere.

Can you explain in more detail what your pull request consists of?

**Comment by mihaisolomon** [comment]
Hey,

The ideea behind this is that if you are going to have multiple users in the platform you need to identify their accounts, that was my logic behind it. Even so it can be extended a little bit more with teams, but that is another talk.

**Comment by lao9s** [comment]
I got it. At the moment, it's premature to implement the team & user functionality. Even if we do it now, we need to do everything from the front end to the backend, not just a small part of the backend. 

Another reason would be that I do not intend to support this functionality in the FREE version. This functionality will be developed and maintained in the PRO version.

**Comment by mihaisolomon** [comment]
Got it. Makes sense.

**Pull request closed without merging**
