### PR TITLE
[WIP] Meetup integration

### PR DESCRIPTION
**Pull request by cweagans**
This is still very much in progress. I'll update it as I have time.

So far:
* Meetup form/credential storage has been added
* Meetup is now included in the unconfigured service alert

### CODE REVIEW

**Comment by lao9s** [comment]
Thank you! I am excited about this integration.
By the way, no need to compile, the compilation is done automatically on the merge.

**Comment by uhlhosting** [comment]
@cweagans nice job!

**Comment by lao9s** [comment]
Hi @cweagans 
How is the integration going?

**Comment by lao9s** [comment]
Hi @cweagans
Could you tell us the status of this PR?

**Comment by cweagans** [comment]
I'm probably not going to continue with this. Meetup requires a Pro account for API access and I no longer manage any Meetup groups.

**Pull request closed without merging**
